name: redefine
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-mp=3.1.0
  - binutils_impl_linux-64=2.40
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cyipopt=1.2.0
  - gcc=12.2.0
  - gcc_impl_linux-64=12.2.0
  - gfortran=12.2.0
  - gfortran_impl_linux-64=12.2.0
  - ipopt=3.14.11
  - kernel-headers_linux-64=2.6.32
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsanitizer=12.2.0
  - libstdcxx-ng=12.2.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - metis=5.1.0
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - ncurses=6.4
  - numpy=1.24.3
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.10.12
  - python_abi=3.10
  - readline=8.2
  - scotch=6.0.9
  - setuptools=68.0.0
  - sqlite=3.41.2
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tzdata=2023c
  - unixodbc=2.3.11
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - cmake==3.26.3
      - filelock==3.12.0
      - idna==3.4
      - jinja2==3.1.2
      - line-profiler==4.1.1
      - lit==16.0.2
      - markupsafe==2.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - pillow==9.5.0
      - requests==2.29.0
      - scipy==1.10.1
      - sympy==1.11.1
      - torch==2.0.0
      - torchaudio==2.0.1
      - torchvision==0.15.1
      - triton==2.0.0
      - typing-extensions==4.5.0
      - urllib3==1.26.15
